# Generated by Django 2.0.5 on 2020-04-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newentry',
            old_name='entry',
            new_name='TodaysEntry',
        ),
        migrations.RenameField(
            model_name='newentry',
            old_name='topic',
            new_name='Topic',
        ),
    ]
