# Generated by Django 2.0.5 on 2020-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0002_auto_20200405_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
