# Generated by Django 2.0.5 on 2020-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='TodaysEntry',
            field=models.TextField(max_length=1000),
        ),
    ]
