# Generated by Django 2.2.10 on 2021-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0005_auto_20200406_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='Topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
