# Generated by Django 2.2.10 on 2021-10-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0006_auto_20211001_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='Author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='Mydiary.User'),
        ),
    ]
