# Generated by Django 2.2.10 on 2021-10-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0009_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='bio',
        ),
    ]
