# Generated by Django 2.2.10 on 2021-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0011_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField(default='hello', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
