# Generated by Django 2.2.10 on 2021-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0012_auto_20211002_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='facebook',
            field=models.URLField(default='facebook.com/'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='instagram',
            field=models.URLField(default='instagram.com/'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='linkedin',
            field=models.URLField(default='linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='twitter',
            field=models.URLField(default='twitter.com/'),
        ),
    ]
