# Generated by Django 2.2.10 on 2021-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0013_auto_20211002_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='TodaysEntry',
            field=models.TextField(default='todaysentry', max_length=1000),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='Topic',
            field=models.CharField(blank=True, default='topic', max_length=30, null=True),
        ),
    ]
