# Generated by Django 2.2.10 on 2021-10-04 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydiary', '0015_auto_20211004_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
